accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/follow/', views.follow, name='follow'),    
    path('profile/update/', views.profile_update, name='profile_update'),    
    path('password/', views.password, name='password'),    
    path('delete/', views.delete, name='delete'),    
    path('update/', views.update, name='update'),    
    path('logout/', views.logout, name='logout'),    
    path('login/', views.login, name='login'),    
    path('signup/', views.signup, name='signup'),    
    # path('recommend/', views.recommend, name='recommend'),    
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_pk>/update_comment/<int:comment_pk>/', views.update_comment, name='update_comment'),
    path('<int:movie_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:movie_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('listings/<int:genre_pk>', views.genre_listings, name="genre_listings"),
    path('listings/', views.listings, name="listings"),
    path('', views.list, name="list"),
]

popcorn/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views



urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Genre(models.Model):
    name = models.TextField()
    def __str__(self):
        return self.name

class Movie(models.Model):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', blank=True)
    movie_id = models.IntegerField(blank=True)
    title = models.TextField(blank=True)
    vote_average = models.FloatField(blank=True)
    popularity = models.FloatField(blank=True)
    poster_path = models.TextField(blank=True)
    original_language = models.TextField(blank=True)
    original_title = models.TextField(blank=True)
    overview = models.TextField(blank=True)
    release_date = models.TextField(blank=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, blank=True)
    backdrop_path = models.TextField(blank=True)
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user_img = models.TextField()
    score = models.IntegerField()
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

movies/forms.py
from django import forms
from .models import Movie, Genre, Comment

class CommentForm(forms.ModelForm):
    score = forms.IntegerField(label="")
    content = forms.CharField(label="")
    class Meta:
        model = Comment
        fields = ['score', 'content',]

movies/views.py
import hashlib
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from .models import Movie, Comment
from .forms import CommentForm

# Create your views here.
def list(request):
    # movies = get_list_or_404(Movie)
    # context = {'movies': movies,}
    return render(request, 'movies/index.html')
    
# def listings(request):
#     movies_list = Movie.objects.all()
#     paginator = Paginator(movies_list, 12)
    
#     page = request.GET.get('page')
#     movies = paginator.get_page(page)
#     context = {'movies': movies,}
#     return render(request, 'movies/listings.html', context)
    
def genre_listings(request, genre_pk):
    movies = Movie.objects.filter(genre=genre_pk).all()
    context = {'movies':movies, }
    return render(request, 'movies/listings.html', context)
    
def listings(request):
    movies = Movie.objects.all()
    context = {'movies': movies,}
    return render(request, 'movies/listings.html', context)
    
    
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    
    comment_form = CommentForm()
    context = {'movie': movie, 'comment_form': comment_form,}
    return render(request, 'movies/listing.html', context) # list말고 디테일로 보내야 함

@login_required    
def create_comment(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.movie_id = movie_pk
            comment.user_img = hashlib.md5(request.user.email.strip().lower().encode('utf-8')).hexdigest()
            comment.save()
    return redirect('movies:detail', movie_pk) # list 말고 디테일로 보내야 함
    
@login_required
def update_comment(request, movie_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user == request.user:
        if request.method == 'POST':
            comment_form = CommentForm(request.POST, instance=comment)
            if comment_form.is_valid():
                comment_form.save()
                return redirect('movies:detail', movie_pk) # list 말고 디테일로 보내야 함
        else:
            comment_form = CommentForm(instance=comment)
        context = {'comment_form': comment_form,}
        return render(request, 'movies/update.html', context) # list 말고 update html 로 보내야 함
    return redirect('movies:detail', movie_pk) # list 말고 디테일로 보내야 함
    
@login_required
def delete_comment(request, movie_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user == request.user:
        if request.method == 'POST':
            comment.delete()
    return redirect('movies:detail', movie_pk) # list 말고 디테일로 보내야 함

movies/templates/movies/_category.html
{% load static %}
<div class="categories">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="categories_container d-flex flex-md-row flex-column align-items-start justify-content-start">
					
					<!-- Category -->
					<div class="category text-center">
						<a href="#boxoffice">
							<div class="d-flex flex-md-column flex-row align-items-md-center align-items-md-start align-items-center justify-content-start">
								<div class="cat_icon"><img style="opacity:0.6;" src="{% static 'movies/images/cinema.PNG' %}" class="svg" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="cat_title">In Theaters</div>
							</div>
						</a>
					</div>

					<!-- Category -->
					<div class="category text-center">
						<a href="{% url 'movies:listings' %}">
							<div class="d-flex flex-md-column flex-row align-items-md-center align-items-md-start align-items-center justify-content-start">
								<div class="cat_icon"><img style="opacity:0.6;" src="{% static 'movies/images/ranking.PNG' %}" class="svg" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="cat_title">Popular</div>
							</div>	
						</a>
					</div>

					<!-- Category -->
					<div class="category text-center">
						<a href="{% url 'people' user %}">
							<div class="d-flex flex-md-column flex-row align-items-md-center align-items-md-start align-items-center justify-content-start">
								<div class="cat_icon"><img style="opacity:0.6;" src="{% static 'movies/images/recommend.PNG' %}" class="svg" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="cat_title">We Recommend</div>
							</div>
						</a>
					</div>

					<!-- Category -->
					<div class="category text-center">
						<a href="http://www.megabox.co.kr/?show=booking&p=step1" target="_blank">
							<div class="d-flex flex-md-column flex-row align-items-md-center align-items-md-start align-items-center justify-content-start">
								<div class="cat_icon"><img style="opacity:0.6;" src="{% static 'movies/images/ticket.png' %}" class="svg" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="cat_title">Ticket</div>
							</div>
						</a>
					</div>

					<!-- Category -->
					<div class="category text-center">
						<a href="#genre">
							<div class="d-flex flex-md-column flex-row align-items-md-center align-items-md-start align-items-center justify-content-start">
								<div class="cat_icon"><img style="opacity:0.6;" src="{% static 'movies/images/popcorn.png' %}" class="svg" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="cat_title">Genre</div>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

movies/templates/movies/_comment_modal.html
<div class="modal fade" id="exampleModal{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">댓글달기</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'movies:update_comment' movie.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="number" class="form-control" placeholder="평점" name="score" min=1 max=10>
                        <small class="form-text text-muted">select between 1 to 10</small>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="코멘트" name="content">
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
            </form>
        </div>
    </div>
</div>

movies/templates/movies/_footer.html
<footer class="footer container_custom">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="footer_container d-flex flex-md-row flex-column align-items-center justify-content-md-start justify-content-center">
					<div class="copyright order-md-1 order-2"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</div>
					<nav class="footer_nav ml-md-auto order-md-2 order-1">
						<ul class="d-flex flex-row align-items-center justify-content-start">
							<li class="active"><a href="{% url 'movies:list' %}">Home</a></li>
							<!--<li><a href="#">About us</a></li>-->
							<li><a href="{% url 'movies:listings' %}">Listings</a></li>
							<!--<li><a href="blog.html">News</a></li>-->
							<!--<li><a href="contact.html">Contact</a></li>-->
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</footer>

movies/templates/movies/_nav.html
{% load static %}

<!-- Menu -->

<div class="menu">
	<div class="menu_container text-right">
		<div class="menu_close">close</div>
		<nav class="menu_nav">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="listings.html">Listings</a></li>
				<li><a href="blog.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>
		<div class="menu_link">
			<a href="#">+Add Listing</a>
		</div>
	</div>
</div>


<header class="header">
	<div class="header_overlay"></div>
	<div class="header_content d-flex flex-row align-items-center justify-content-start">
		
		<!-- Logo -->
		<div class="logo"><a href="{% url 'movies:list' %}">Popcorn<span>Overflow</span><span>+</span></a></div>

		<!-- Header Nav -->
		<div class="header_right d-flex flex-row align-items-center justify-content-start ml-auto">
			<nav class="main_nav">
				<ul class="d-flex flex-row align-items-center justify-content-start">
					<li class="active"><a href="{% url 'movies:list' %}">Home</a></li>
					<!--<li><a href="#">About us</a></li>-->
					<!--<li><a href="{% url 'movies:listings' %}">Listings</a></li>-->
					<!--<li><a href="blog.html">News</a></li>-->
					<!--<li><a href="contact.html">Contact</a></li>-->
				</ul>
			</nav>
			<div class="add_listing text-center trans_200"><a href="{% url 'movies:listings' %}">Listings</a></div>
			<div class="log_reg">
				<ul class="d-flex flex-row align-items-center justify-content-start">
					{% if user.is_authenticated %}
	                    <li><a href="{% url 'people' user.username %}">{{ user.username }}</a></li>
	                    <li><a href="{% url 'people' user.username %}">MyPage</a></li>
	                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
	                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
	                    <li><a href="{% url 'accounts:signup' %}">Register</a></li>
                    {% endif %}
				</ul>
			</div>
			<div class="hamburger">
				<i class="fa fa-bars trans_200"></i>
			</div>
		</div>

	</div>
</header>

movies/templates/movies/_slide.html
{% load static %}
<div class="home">
			
	<!-- Home Slider -->
	<div class="home_slider_container">
		<div class="owl-carousel owl-theme home_slider">
			
			<!-- Slide -->
			<div class="slide">
				<div class="background_image" style="background-image:url({% static 'movies/images/bg3_p.jpg' %})"></div>
				<div class="home_container">
					<div class="container">
						<div class="row">
							<div class="col-xl-8 offset-xl-2">
								<div class="home_content text-center">
									<div class="home_title"><h1>Popcorn <span>Overflow</span></h1></div>
									<div class="search_form_container">
										<form action="#" class="search_form" id="search_form">
											<div class="d-flex flex-sm-row flex-column align-items-sm-start align-items-center justify-content-sm-between">
												<input type="text" class="search_input" placeholder="Which movie are you looking for?" required="required">
												<button class="search_button">Search</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Slide -->
			<div class="slide">
				<div class="background_image" style="background-image:url({% static 'movies/images/bg2_p.jpg' %})"></div>
				<div class="home_container">
					<div class="container">
						<div class="row">
							<div class="col-xl-8 offset-xl-2">
								<div class="home_content text-center">
									<div class="home_title"><h1>Popcorn <span>Overflow</span></h1></div>
									<div class="search_form_container">
										<form action="#" class="search_form" id="search_form">
											<div class="d-flex flex-sm-row flex-column align-items-sm-start align-items-center justify-content-sm-between">
												<input type="text" class="search_input" placeholder="Which movie are you looking for?" required="required">
												<button class="search_button">Search</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Slide -->
			<div class="slide">
				<div class="background_image" style="background-image:url({% static 'movies/images/bg1_p.jpg' %})"></div>
				<div class="home_container">
					<div class="container">
						<div class="row">
							<div class="col-xl-8 offset-xl-2">
								<div class="home_content text-center">
									<div class="home_title"><h1>Popcorn <span>Overflow</span></h1></div>
									<div class="search_form_container">
										<form action="#" class="search_form" id="search_form">
											<div class="d-flex flex-sm-row flex-column align-items-sm-start align-items-center justify-content-sm-between">
												<input type="text" class="search_input" placeholder="Which movie are you looking for?" required="required">
												<button class="search_button">Search</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>

		<!-- Home Slider Dots -->

		<div class="home_slider_dots">
			<ul id="home_slider_custom_dots" class="home_slider_custom_dots">
				<li class="home_slider_custom_dot active">01.</li>
				<li class="home_slider_custom_dot">02.</li>
				<li class="home_slider_custom_dot">03.</li>
			</ul>
		</div>

	</div>
</div>

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/bootstrap-4.1.2/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/responsive.css' %}">
{% endblock %}

{% block content %}
<!-- Menu -->
<div class="menu">
	<div class="menu_container text-right">
		<div class="menu_close">close</div>
		<nav class="menu_nav">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="listings.html">Listings</a></li>
				<li><a href="blog.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>
		<div class="menu_link">
			<a href="#">+Add Listing</a>
		</div>
	</div>
</div>
<div class="super_container">
	{% include 'movies/_nav.html' %}
	
	<div class="super_container_inner">
		<div class="super_overlay"></div>

		<!-- Home -->
		{% include 'movies/_slide.html' %}
		

		<!-- Categories -->
		{% include 'movies/_category.html' %}
		

		<!-- Boxoffice -->

		<div id="boxoffice" class="locations container_custom">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="section_title text-center"><h1>In Theaters Now</h1></div>
						<div class="locations_container d-flex flex-row align-items-start justify-content-between flex-wrap">
							
							<!-- Location -->
							<div class="location">
								<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/sPZxApU8d90Czd11S60UqOhuP9R.jpg" alt="">
								<div class="location_title text-center"><div><a href="{% url 'movies:detail' 2 %}">샤잠!<div>+</div></a></div></div>
							</div>

							<!-- Location -->
							<div class="location">
								<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/n78LK2t1uQP68Ud0VXHRe0HmKOp.jpg" alt="">
								<div class="location_title text-center"><div><a href="{% url 'movies:detail' 1 %}">어벤져스: 엔드게임<div>+</div></a></div></div>
							</div>

							<!-- Location -->
							<div class="location">
								<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/8Vb7PJ2aUzel5iQ6R2Jxe4MTWac.jpg" alt="">
								<div class="location_title text-center"><div><a href="{% url 'movies:detail' 4 %}">명탐정 피카츄<div>+</div></a></div></div>
							</div>

							<!-- Location -->
							<div class="location">
								<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/gua7L4syuPUZeG35lpu5xvOzquH.jpg" alt="">
								<div class="location_title text-center"><div><a href="{% url 'movies:detail' 10 %}">헬보이<div>+</div></a></div></div>
							</div>

							<!-- Location -->
							<div class="location">
								<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/4MDB6jJl3U7xK1Gw64zIqt9pQA4.jpg" alt="">
								<div class="location_title text-center"><div><a href="{% url 'movies:detail' 22 %}">리틀<div>+</div></a></div></div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Food -->

		<div id="genre" class="food container_custom">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="section_title text-center"><h1>Explore by Genre</h1></div>
						<div class="grid_container grid">
							
							<!-- Grid Item -->
							<div class="grid-item grid_large">
								<div class="food_item">
									<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 28 %}">액션</a></div>
									<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/original/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg)"></div>
								</div>
							</div>

							<!-- Grid Item -->
							<div class="grid-item grid_small">
								<div class="food_item">
									<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 10749 %}">로맨스</a></div> 
									<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/w600_and_h900_bestv2/3l6wpIL6wiq593MnV3AhIhPjww2.jpg)"></div>
								</div>
							</div>

							<!-- Grid Item -->
							<div class="grid-item grid_medium">
								<div>
									<div class="grid_half">
										<div class="food_item">
											<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 14 %}">판타지</a></div>
											<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/original/2cUsDz4TzFYHrKktT1bKHHQ7Cgm.jpg)"></div>
										</div>
									</div>
									<div class="grid_half">
										<div class="food_item">
											<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 16 %}">애니메이션</a></div>
											<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/w500_and_h282_face/aUVCJ0HkcJIBrTJYPnTXta8h9Co.jpg)"></div>
										</div>
									</div>
								</div>
							</div>

							<!-- Grid Item -->
							<div class="grid-item grid_medium">
								<div class="food_item">
									<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 878 %}">SF</a></div>
									<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/w600_and_h900_bestv2/a1XTVjEiShbX1XE6Uvaho49gw3l.jpg)"></div>
								</div>
							</div>

							<!-- Grid Item -->
							<div class="grid-item grid_small">
								<div class="food_item">
									<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 53 %}">스릴러</a></div>
									<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/w600_and_h900_bestv2/yxdY0NaunKDNcpIUFhdgk9z9Y5r.jpg)"></div>
								</div>
							</div>

							<!-- Grid Item -->
							<div class="grid-item grid_large">
								<div class="food_item">
									<div class="food_item_tag"><a href="{% url 'movies:genre_listings' 35 %}">코미디</a></div>
									<div class="background_image" style="background-image:url(https://image.tmdb.org/t/p/original/7gwIbnB2j45wSC3esSzkRzfwcws.jpg)"></div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- How it works -->

		<div class="how container_custom">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="section_title text-center"><h1>How Popcorn<span>Overflow+</span> works</h1></div>
						<div class="icon_box_container d-flex flex-row align-items-start justify-content-between flex-wrap">
							
							<!-- Icon Box -->
							<div class="icon_box d-flex flex-column align-items-center justify-content-start text-center">
								<div class="icon_box_num">01.</div>
								<div class="icon_box_icon"><img src="{% static 'movies/images/icon_6.svg' %}" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="icon_box_title">Tell us about you</div>
								<div class="icon_box_text">
									<p>Write reviews on your favorite movies and follow other people for your happy popcorn time.</p>
								</div>
							</div>

							<!-- Icon Box -->
							<div class="icon_box d-flex flex-column align-items-center justify-content-start text-center">
								<div class="icon_box_num">02.</div>
								<div class="icon_box_icon"><img src="{% static 'movies/images/icon_7.svg' %}" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="icon_box_title">Find your pick</div>
								<div class="icon_box_text">
									<p>Find the best movie that suits you. We recommend movies with our super cool recommendation engine.</p>
								</div>
							</div>

							<!-- Icon Box -->
							<div class="icon_box d-flex flex-column align-items-center justify-content-start text-center">
								<div class="icon_box_num">03.</div>
								<div class="icon_box_icon"><img src="{% static 'movies/images/icon_8.svg' %}" alt="https://www.flaticon.com/authors/monkik"></div>
								<div class="icon_box_title">Go & have fun</div>
								<div class="icon_box_text">
									<p>Happy popcorn time! Fetch your favorite popcorn, sit back, relax, have fun:)</p>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- CTA -->

		<div class="cta container_custom">
			<div class="parallax_background" data-image-src="{% static 'movies/images/background.jpg' %}"></div>
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="cta_content">
							<div class="cta_title"><h1>Fetch your popcorn now!</h1></div>
							<div class="cta_text">
								<p>Donec cursus, risus non fermentum lacinia, felis lectus interdum velit, in pulvinar enim justo at sem. Quisque ut semper neque. Suspendisse quam est, consequat ullamcorper tellus et, fauci bus laoreet nibh.</p>
							</div>
							<div class="button cta_button"><a href="{% url 'people' user %}">Pop Corns</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- CTA 2 -->

		<div class="cta_2">
			<div class="container">
				<div class="row row-lg-eq-height">
					<div class="col-lg-9 cta_2_col">
						<div class="cta_2_content">
							<div class="cta_2_title"><h1>Get the Popcorn<span>Overflow+</span> App</h1></div>
							<div class="cta_2_text">
								<p>Donec cursus, risus non fermentum lacinia, felis lectus interdum velit, in pulvinar enim justo at sem. Quisque ut semper neque. Suspendisse quam est, consequat ullamcorper tellus et, fauci bus laoreet nibh.Donec cursus, risus non fermentum lacinia, felis lectus interdum velit, in pulvinar enim justo at sem.</p>
							</div>
							<div class="store_links d-flex flex-row align-items-start justify-content-start flex-wrap">
								<div class="store_link"><a href="#"><img src="{% static 'movies/images/store_1.jpg' %}" alt=""></a></div>
								<div class="store_link"><a href="#"><img src="{% static 'movies/images/store_2.jpg' %}" alt=""></a></div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 cta_2_col">
						<div class="cta_2_image">
							<img src="{% static 'movies/images/cta_2.jpg' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Clients -->

		<div class="clients">
			<div class="container">
				<div class="row">
					<div class="col">

						<!-- Clients Slider -->
						<div class="clients_slider_container">
							<div class="owl-carousel owl-theme clients_slider">
								
								<!-- Slide -->
								<div class="slide">
									<div class="client_image"><a href="#"><img src="{% static 'movies/images/client_1.jpg' %}" alt=""></a></div>
								</div>

								<!-- Slide -->
								<div class="slide">
									<div class="client_image"><a href="#"><img src="{% static 'movies/images/client_2.jpg' %}" alt=""></a></div>
								</div>

								<!-- Slide -->
								<div class="slide">
									<div class="client_image"><a href="#"><img src="{% static 'movies/images/client_3.jpg' %}" alt=""></a></div>
								</div>

								<!-- Slide -->
								<div class="slide">
									<div class="client_image"><a href="#"><img src="{% static 'movies/images/client_4.jpg' %}" alt=""></a></div>
								</div>

								<!-- Slide -->
								<div class="slide">
									<div class="client_image"><a href="#"><img src="{% static 'movies/images/client_5.jpg' %}" alt=""></a></div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Footer -->

		{% include 'movies/_footer.html' %}
	</div>
		
</div>
{% endblock %}


