accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/follow/', views.follow, name='follow'),    
    path('profile/update/', views.profile_update, name='profile_update'),    
    path('password/', views.password, name='password'),    
    path('delete/', views.delete, name='delete'),    
    path('update/', views.update, name='update'),    
    path('logout/', views.logout, name='logout'),    
    path('login/', views.login, name='login'),    
    path('signup/', views.signup, name='signup'),    
    # path('recommend/', views.recommend, name='recommend'),    
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_pk>/update_comment/<int:comment_pk>/', views.update_comment, name='update_comment'),
    path('<int:movie_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:movie_pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('listings/<int:genre_pk>', views.genre_listings, name="genre_listings"),
    path('listings/', views.listings, name="listings"),
    path('', views.list, name="list"),
]

popcorn/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views



urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=10, blank=True)
    introduction = models.TextField(blank=True)
    
    def __str__(self):
        return self.nickname
        
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserCustomCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):      # Meta 클래스도 상속받을수 있다.
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2', ]
    
class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'introduction']
        

        

accounts/views.py
import hashlib
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import Profile
from movies.models import Movie, Comment, Genre
from .forms import UserCustomChangeForm, ProfileForm, UserCustomCreationForm



# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
      
    if request.method == 'POST':
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('movies:list')
    else:
        form = UserCustomCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)
    


def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
        
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.POST.get('next') or 'movies:list')
    
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)
    
def logout(request):
    auth_logout(request)
    return redirect('movies:list')

def people(request, username):
    # if request.user.is_authenticated:
    #     gravatar_url = hashlib.md5(request.user.email.strip().lower().encode('utf-8')).hexdigest()
    # else:
    #     gravatar_url = None # 변수 선언은 해야하니까 None 값을 할당.
    
    people = get_object_or_404(get_user_model(), username=username)
    gravatar_url = hashlib.md5(people.email.strip().lower().encode('utf-8')).hexdigest()
    followers = people.followers.all()
    followings = people.followings.all()
    
    recommend_movies = Movie.objects.filter().all()[:10]
    context = {
            'people':people,
            'gravatar_url': gravatar_url,
            'recommend_movies': recommend_movies,
            'movie_genre' : "",
            'follower_movies': "",
            'following_movies' : "",
            
        }
    
    if followers:
        context['follower_movies'] = Comment.objects.filter(user__in=followers).order_by('-score')[:10]
        
    if followings:
        context['following_movies'] = Comment.objects.filter(user__in=followings).order_by('-score')[:10]
        
    
    
    # 추천
    user_comment = Comment.objects.filter(user=people).order_by('-score').values_list('movie', flat=True).distinct()[:1]
    if user_comment:
        movie_genre = Movie.objects.filter(pk=user_comment[0]).order_by('pk').values_list('genre', flat=True).distinct()
        context['recommend_movies'] = Movie.objects.filter(genre=movie_genre[0]).all()[:10]
        context['movie_genre'] = Genre.objects.filter(pk=movie_genre[0]).all()[0]
        
    return render(request, 'accounts/profile.html', context)
    
# @require_POST
@login_required 
def update(request):
    if request.method == 'POST':
        user_change_form = UserCustomChangeForm(request.POST, instance = request.user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('people', request.user.username)
        
        
    else:
        user_change_form = UserCustomChangeForm(instance = request.user)
        
    context={
        'user_change_form':user_change_form,
    }
    return render(request, 'accounts/update.html', context)
    
@login_required 
def delete(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
    return redirect('movies:list')
    
@login_required 
def password(request):
    if request.method == "POST":
        password_change_form = PasswordChangeForm(user=request.user, data=request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:list')
            
    else:
        password_change_form = PasswordChangeForm(request.user)
    context = {
        'password_change_form':password_change_form,
    }
    return render(request, 'accounts/password.html', context)
    

@login_required
def profile_update(request):
    profile = Profile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('people', request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    context = {'profile_form': profile_form,}
    return render(request, 'accounts/profile_update.html', context)
    
@login_required
def follow(request, user_pk):
    people = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user in people.followers.all():
        people.followers.remove(request.user)
    else:
        people.followers.add(request.user)
    return redirect('people', people.username)
    

accounts/templates/accounts/_modal.html
<div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <textarea>제 1 장 총 칙

 

제 1 조 (목적)
이 약관은 {COMPANY_NAME}(이하 "사이트"라 합니다)에서 제공하는 인터넷서비스(이하 "서비스"라 합니다)의 이용 조건 및 절차에 관한 기본적인 사항을 규정함을 목적으로 합니다.

 

제 2 조 (약관의 효력 및 변경)
① 이 약관은 서비스 화면이나 기타의 방법으로 이용고객에게 공지함으로써 효력을 발생합니다.
② 사이트는 이 약관의 내용을 변경할 수 있으며, 변경된 약관은 제1항과 같은 방법으로 공지 또는 통지함으로써 효력을 발생합니다.

 

제 3 조 (용어의 정의)
이 약관에서 사용하는 용어의 정의는 다음과 같습니다.
① 회원 : 사이트와 서비스 이용계약을 체결하거나 이용자 아이디(ID)를 부여받은 개인 또는 단체를 말합니다.
② 신청자 : 회원가입을 신청하는 개인 또는 단체를 말합니다.
③ 아이디(ID) : 회원의 식별과 서비스 이용을 위하여 회원이 정하고 사이트가 승인하는 문자와 숫자의 조합을 말합니다.
④ 비밀번호 : 회원이 부여 받은 아이디(ID)와 일치된 회원임을 확인하고, 회원 자신의 비밀을 보호하기 위하여 회원이 정한 문자와 숫자의 조합을 말합니다.
⑤ 해지 : 사이트 또는 회원이 서비스 이용계약을 취소하는 것을 말합니다.

 

제 2 장 서비스 이용계약

 

제 4 조 (이용계약의 성립)
① 이용약관 하단의 동의 버튼을 누르면 이 약관에 동의하는 것으로 간주됩니다.
② 이용계약은 서비스 이용희망자의 이용약관 동의 후 이용 신청에 대하여 사이트가 승낙함으로써 성립합니다.

 

제 5 조 (이용신청)
① 신청자가 본 서비스를 이용하기 위해서는 사이트 소정의 가입신청 양식에서 요구하는 이용자 정보를 기록하여 제출해야 합니다.
② 가입신청 양식에 기재하는 모든 이용자 정보는 모두 실제 데이터인 것으로 간주됩니다. 실명이나 실제 정보를 입력하지 않은 사용자는 법적인 보호를 받을 수 없으며, 서비스의 제한을 받을 수 있습니다.

 

제 6 조 (이용신청의 승낙)
① 사이트는 신청자에 대하여 제2항, 제3항의 경우를 예외로 하여 서비스 이용신청을 승낙합니다.
② 사이트는 다음에 해당하는 경우에 그 신청에 대한 승낙 제한사유가 해소될 때까지 승낙을 유보할 수 있습니다.
가. 서비스 관련 설비에 여유가 없는 경우
나. 기술상 지장이 있는 경우
다. 기타 사이트가 필요하다고 인정되는 경우
③ 사이트는 신청자가 다음에 해당하는 경우에는 승낙을 거부할 수 있습니다.
가. 다른 개인(사이트)의 명의를 사용하여 신청한 경우
나. 이용자 정보를 허위로 기재하여 신청한 경우
다. 사회의 안녕질서 또는 미풍양속을 저해할 목적으로 신청한 경우
라. 기타 사이트 소정의 이용신청요건을 충족하지 못하는 경우

 

제 7 조 (이용자정보의 변경)
회원은 이용 신청시에 기재했던 회원정보가 변경되었을 경우에는, 온라인으로 수정하여야 하며 변경하지 않음으로 인하여 발생되는 모든 문제의 책임은 회원에게 있습니다.

 

제 3 장 계약 당사자의 의무

 

제 8 조 (사이트의 의무)
① 사이트는 회원에게 각 호의 서비스를 제공합니다.
가. 신규서비스와 도메인 정보에 대한 뉴스레터 발송
나. 추가 도메인 등록시 개인정보 자동 입력
다. 도메인 등록, 관리를 위한 각종 부가서비스
② 사이트는 서비스 제공과 관련하여 취득한 회원의 개인정보를 회원의 동의없이 타인에게 누설, 공개 또는 배포할 수 없으며, 서비스관련 업무 이외의 상업적 목적으로 사용할 수 없습니다. 단, 다음 각 호의 1에 해당하는 경우는 예외입니다.
가. 전기통신기본법 등 법률의 규정에 의해 국가기관의 요구가 있는 경우
나. 범죄에 대한 수사상의 목적이 있거나 정보통신윤리 위원회의 요청이 있는 경우
다. 기타 관계법령에서 정한 절차에 따른 요청이 있는 경우
③ 사이트는 이 약관에서 정한 바에 따라 지속적, 안정적으로 서비스를 제공할 의무가 있습니다.

 

제 9 조 (회원의 의무)
① 회원은 서비스 이용 시 다음 각 호의 행위를 하지 않아야 합니다.
가. 다른 회원의 ID를 부정하게 사용하는 행위
나. 서비스에서 얻은 정보를 사이트의 사전승낙 없이 회원의 이용 이외의 목적으로 복제하거나 이를 변경, 출판 및 방송 등에 사용하거나 타인에게 제공하는 행위
다. 사이트의 저작권, 타인의 저작권 등 기타 권리를 침해하는 행위
라. 공공질서 및 미풍양속에 위반되는 내용의 정보, 문장, 도형 등을 타인에게 유포하는 행위
마. 범죄와 결부된다고 객관적으로 판단되는 행위
바. 기타 관계법령에 위배되는 행위
② 회원은 관계법령, 이 약관에서 규정하는 사항, 서비스 이용 안내 및 주의 사항을 준수하여야 합니다.
③ 회원은 내용별로 사이트가 서비스 공지사항에 게시하거나 별도로 공지한 이용 제한 사항을 준수하여야 합니다.

 

제 4 장 서비스 제공 및 이용

 

제 10 조 (회원 아이디(ID)와 비밀번호 관리에 대한 회원의 의무)
① 아이디(ID)와 비밀번호에 대한 모든 관리는 회원에게 책임이 있습니다. 회원에게 부여된 아이디(ID)와 비밀번호의 관리소홀, 부정사용에 의하여 발생하는 모든 결과에 대한 전적인 책임은 회원에게 있습니다.
② 자신의 아이디(ID)가 부정하게 사용된 경우 또는 기타 보안 위반에 대하여, 회원은 반드시 사이트에 그 사실을 통보해야 합니다.

 

제 11 조 (서비스 제한 및 정지)
① 사이트는 전시, 사변, 천재지변 또는 이에 준하는 국가비상사태가 발생하거나 발생할 우려가 있는 경우와 전기통신사업법에 의한 기간통신 사업자가 전기통신서비스를 중지하는 등 기타 불가항력적 사유가 있는 경우에는 서비스의 전부 또는 일부를 제한하거나 정지할 수 있습니다.
② 사이트는 제1항의 규정에 의하여 서비스의 이용을 제한하거나 정지할 때에는 그 사유 및 제한기간 등을 지체없이 회원에게 알려야 합니다.

 

제5장 계약사항의 변경, 해지

 

제 12 조 (정보의 변경)
회원이 주소, 비밀번호 등 고객정보를 변경하고자 하는 경우에는 홈페이지의 회원정보 변경 서비스를 이용하여 변경할 수 있습니다.

 

제 13 조 (계약사항의 해지)
회원은 서비스 이용계약을 해지할 수 있으며, 해지할 경우에는 본인이 직접 서비스를 통하거나 전화 또는 온라인 등으로 사이트에 해지신청을 하여야 합니다. 사이트는 해지신청이 접수된 당일부터 해당 회원의 서비스 이용을 제한합니다. 사이트는 회원이 다음 각 항의 1에 해당하여 이용계약을 해지하고자 할 경우에는 해지조치 7일전까지 그 뜻을 이용고객에게 통지하여 소명할 기회를 주어야 합니다.
① 이용고객이 이용제한 규정을 위반하거나 그 이용제한 기간 내에 제한 사유를 해소하지 않는 경우
② 정보통신윤리위원회가 이용해지를 요구한 경우
③ 이용고객이 정당한 사유 없이 의견진술에 응하지 아니한 경우
④ 타인 명의로 신청을 하였거나 신청서 내용의 허위 기재 또는 허위서류를 첨부하여 이용계약을 체결한 경우
사이트는 상기 규정에 의하여 해지된 이용고객에 대해서는 별도로 정한 기간동안 가입을 제한할 수 있습니다.

 

제6장 손해배상

 

제 14 조 (면책조항)
① 사이트는 회원이 서비스 제공으로부터 기대되는 이익을 얻지 못하였거나 서비스 자료에 대한 취사선택 또는 이용으로 발생하는 손해 등에 대해서는 책임이 면제됩니다.
② 사이트는 회원의 귀책사유나 제3자의 고의로 인하여 서비스에 장애가 발생하거나 회원의 데이터가 훼손된 경우에 책임이 면제됩니다.
③ 사이트는 회원이 게시 또는 전송한 자료의 내용에 대해서는 책임이 면제됩니다.
④ 상표권이 있는 도메인의 경우, 이로 인해 발생할 수도 있는 손해나 배상에 대한 책임은 구매한 회원 당사자에게 있으며, 사이트는 이에 대한 일체의 책임을 지지 않습니다.

 

제 15 조 (관할법원)

 

서비스와 관련하여 사이트와 회원간에 분쟁이 발생할 경우 사이트의 본사 소재지를 관할하는 법원을 관할법원으로 합니다.

 

[부칙]

 

(시행일) 이 약관은 2015년 01월부터 시행합니다.</textarea>
      
    </div>
  </div>
</div>

  

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block css %}
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/main_styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/stylesheets/auth_login.css' %}">
{% endblock %}

{% block content %}
<!-- Menu -->
<div class="menu">
	<div class="menu_container text-right">
		<div class="menu_close">close</div>
		<nav class="menu_nav">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="listings.html">Listings</a></li>
				<li><a href="blog.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>
		<div class="menu_link">
			<a href="#">+Add Listing</a>
		</div>
	</div>
</div>
<!--<div class="super_container">-->
	{% include 'movies/_nav.html' %}
	<div class="container">
		<div class="d-flex justify-content-center h-100">
			<div class="card">
				<div class="card-header">
					<h3 class="mt-5">Sign In</h3>
					<div class="d-flex justify-content-end social_icon">
						<!--<span><i class="fab fa-facebook-square"></i></span>-->
						<!--<span><i class="fab fa-google-plus-square"></i></span>-->
						<!--<span><i class="fab fa-twitter-square"></i></span>-->
						<!--<a href="{% provider_login_url 'kakao' method='oauth2' %}" class="btn btn-warning">카카오로그인</a>-->
						<a href="{% provider_login_url 'kakao' method='oauth2' %}">
							<img src="{% static 'accounts/images/kakaolink_btn_medium.png' %}" ></img>
						</a>
						
					</div>
				</div>
				<div class="card-body">
					<form action="" method="POST" enctype="multipart/form-data">
					    {% csrf_token %}
						<div class="input-group form-group">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" class="form-control" placeholder="username" name="username">
							
						</div>
						<div class="input-group form-group mt-3">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" class="form-control" placeholder="password" name="password">
						</div>
						<!--<div class="row align-items-center remember">-->
						<!--	<input type="checkbox">Remember Me-->
						<!--</div>-->
						<div class="form-group mt-3">
							<input type="submit" value="Login" class="btn float-right login_btn">
						</div>
					</form>
				</div>
				<div class="card-footer">
					<div class="d-flex justify-content-center links">
						Don't have an account?<a href="{% url 'accounts:signup' %}">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center">
						
					</div>
				</div>
				
			</div>
		</div>
	</div>
	{% include 'movies/_footer.html' %}
<!--</div>-->
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block css %}
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/main_styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/stylesheets/auth_login.css' %}">
{% endblock %}

{% block content %}
<!-- Menu -->
<div class="menu">
	<div class="menu_container text-right">
		<div class="menu_close">close</div>
		<nav class="menu_nav">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="listings.html">Listings</a></li>
				<li><a href="blog.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>
		<div class="menu_link">
			<a href="#">+Add Listing</a>
		</div>
	</div>
</div>
<!--<div class="super_container">-->
{% include 'movies/_nav.html' %}
	
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
		    <div class="card-header">
				<h3></h3>

			</div>
			<div class="card-header">
				<h2 class="text-center text-light">Password Change</h2>

			</div>
			<div class="card-body">
				<form action="" method="POST" enctype="multipart/form-data">
				    {% csrf_token %}
					<!-- password1 -->
                    <div class="d-flex justify-content-center input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class='fa fa-key ml-2' style='font-size:20px'></i></span>
                            <input type="password" class="form-control" placeholder="기존 비밀번호" id="tbSifre" name="old_password" style="width: 325px" required>
                        </div>         
                    </div>
                    <div class="d-flex justify-content-center input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class='fa fa-key ml-2' style='font-size:20px'></i></span>
                            <input type="password" class="form-control" placeholder="새 비밀번호" id="tbSifre" name="new_password1" style="width: 325px" required>
                        </div>         
                    </div>
                    <!-- password2 -->
                    <div class="d-flex justify-content-center input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class='fa fa-key ml-2' style='font-size:20px'></i></span>
                            <input type="password" class="form-control" placeholder="새 비밀번호 확인" id="tbTekrarSifre" name="new_password2" style="width: 325px" required>                 
                        </div>         
                    </div>
                    <div class="form-group">
					    <input type="submit" value="change" class="btn float-right login_btn">
				    </div>
				</form>
			</div>
			
			
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/recommend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    {% for comment in user_comment %}
    <h1>
        {{ comment.score }}
    </h1>
    {% endfor %}
</body>
</html>

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
 {% block css %}
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/main_styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'movies/styles/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/stylesheets/auth_login.css' %}">
{% endblock %}

{% block content %}
<!-- Menu -->
<div class="menu">
	<div class="menu_container text-right">
		<div class="menu_close">close</div>
		<nav class="menu_nav">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="listings.html">Listings</a></li>
				<li><a href="blog.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>
		<div class="menu_link">
			<a href="#">+Add Listing</a>
		</div>
	</div>
</div>
<!--<div class="super_container">-->
{% include 'movies/_nav.html' %}
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
		    <div class="card-header">
				<h3></h3>

			</div>
			<div class="card-header">
				<h2 class="text-center text-light">User Change</h2>

			</div>
			<div class="card-body">
				<form action="" method="POST" enctype="multipart/form-data">
				    {% csrf_token %}
					
                    <div class="d-flex justify-content-center input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class='fa fa-envelope' style='font-size:26px'></i></span>
                            <input type="email" class="form-control" placeholder="email" id="tbSifre" name="email" style="width: 325px" required>
                        </div>         
                    </div>
                    <div class="d-flex justify-content-center input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-signature" style='font-size:26px'></i></span>
                            <input type="text" class="form-control" placeholder="first_name" id="tbSifre" name="first_name" style="width: 325px" required>
                        </div>         
                    </div>
                    
                    <div class="d-flex justify-content-center input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-signature" style='font-size:26px'></i></span>
                            <input type="text" class="form-control" placeholder="last_name" id="tbTekrarSifre" name="first_name" style="width: 325px" required>                 
                        </div>         
                    </div>
                    <div class="form-group">
					    <input type="submit" value="change" class="btn float-right login_btn">
				    </div>
				</form>
				<form action="{% url 'accounts:delete' %}" method="POST" onsubmit="return confirm('R U Sure')">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">회원탈퇴</button>
                </form>
			</div>
			
			
		</div>
	</div>
</div>

{% include 'movies/_footer.html' %}
<!--</div>-->
{% endblock %}